FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api.py .
COPY static/swagger.json ./static/swagger.json

EXPOSE 5000

CMD ["python", "api.py"]